export { default as Home } from './home/Home'
export { default as About } from './about/About'
export { default as Contacts } from './contacts/Contacts'
export { default as Basket } from './basket/Basket'
export { default as NotFound } from './notFound/NotFound'
export { default as Catalog } from './catalog/Catalog'
