export {default as Home} from './home/Home'
export {default as About} from './about/About'
export {default as Contacts} from './contacts/Contacts'
export {default as Products} from './products/Products'
export {default as Basket} from './basket/Basket'
export {default as NotFound} from './notFound/NotFound'
